//
// HeartbeatResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ClientTokensDict: Codable, JSONEncodable, Hashable {
    public var ENABLED: Bool
    public init(ENABLED: Bool) { self.ENABLED = ENABLED }
}

public struct HeartbeatResponse: Codable, JSONEncodable, Hashable {

    public var SYSTEM: SystemDict
    public var METADATA_SOURCES: MetadataSourcesDict
    public var FILESYSTEM: FilesystemDict
    public var EMULATION: EmulationDict
    public var FRONTEND: FrontendDict
    public var OIDC: OIDCDict
    public var CLIENT_TOKENS: ClientTokensDict?

    public init(SYSTEM: SystemDict, METADATA_SOURCES: MetadataSourcesDict, FILESYSTEM: FilesystemDict, EMULATION: EmulationDict, FRONTEND: FrontendDict, OIDC: OIDCDict, CLIENT_TOKENS: ClientTokensDict? = nil) {
        self.SYSTEM = SYSTEM
        self.METADATA_SOURCES = METADATA_SOURCES
        self.FILESYSTEM = FILESYSTEM
        self.EMULATION = EMULATION
        self.FRONTEND = FRONTEND
        self.OIDC = OIDC
        self.CLIENT_TOKENS = CLIENT_TOKENS
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case SYSTEM
        case METADATA_SOURCES
        case FILESYSTEM
        case EMULATION
        case FRONTEND
        case OIDC
        case CLIENT_TOKENS
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        SYSTEM = try container.decode(SystemDict.self, forKey: .SYSTEM)
        METADATA_SOURCES = try container.decodeIfPresent(MetadataSourcesDict.self, forKey: .METADATA_SOURCES) ?? MetadataSourcesDict()
        FILESYSTEM = try container.decodeIfPresent(FilesystemDict.self, forKey: .FILESYSTEM) ?? FilesystemDict()
        EMULATION = try container.decodeIfPresent(EmulationDict.self, forKey: .EMULATION) ?? EmulationDict()
        FRONTEND = try container.decodeIfPresent(FrontendDict.self, forKey: .FRONTEND) ?? FrontendDict()
        OIDC = try container.decodeIfPresent(OIDCDict.self, forKey: .OIDC) ?? OIDCDict()
        CLIENT_TOKENS = try container.decodeIfPresent(ClientTokensDict.self, forKey: .CLIENT_TOKENS)
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(SYSTEM, forKey: .SYSTEM)
        try container.encode(METADATA_SOURCES, forKey: .METADATA_SOURCES)
        try container.encode(FILESYSTEM, forKey: .FILESYSTEM)
        try container.encode(EMULATION, forKey: .EMULATION)
        try container.encode(FRONTEND, forKey: .FRONTEND)
        try container.encode(OIDC, forKey: .OIDC)
        try container.encodeIfPresent(CLIENT_TOKENS, forKey: .CLIENT_TOKENS)
    }
}

