//
// SiblingRomSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SiblingRomSchema: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var name: String?
    public var fsNameNoTags: String
    public var fsNameNoExt: String
    public var sortComparator: String

    public init(id: Int, name: String?, fsNameNoTags: String, fsNameNoExt: String, sortComparator: String) {
        self.id = id
        self.name = name
        self.fsNameNoTags = fsNameNoTags
        self.fsNameNoExt = fsNameNoExt
        self.sortComparator = sortComparator
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case fsNameNoTags = "fs_name_no_tags"
        case fsNameNoExt = "fs_name_no_ext"
        case sortComparator = "sort_comparator"
    }

    // Decodable protocol methods
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(Int.self, forKey: .id)
        name = try container.decodeIfPresent(String.self, forKey: .name)
        fsNameNoTags = container.decodeFlexibleString(forKey: .fsNameNoTags, default: "")
        fsNameNoExt = container.decodeFlexibleString(forKey: .fsNameNoExt, default: "")
        sortComparator = container.decodeFlexibleString(forKey: .sortComparator, default: "")
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(fsNameNoTags, forKey: .fsNameNoTags)
        try container.encode(fsNameNoExt, forKey: .fsNameNoExt)
        try container.encode(sortComparator, forKey: .sortComparator)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SiblingRomSchema: Identifiable {}
