//
// SystemDict.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SystemDict: Codable, JSONEncodable, Hashable {

    public var VERSION: String
    public var SHOW_SETUP_WIZARD: Bool

    public init(VERSION: String = "", SHOW_SETUP_WIZARD: Bool = false) {
        self.VERSION = VERSION
        self.SHOW_SETUP_WIZARD = SHOW_SETUP_WIZARD
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        VERSION = try container.decode(String.self, forKey: .VERSION)
        SHOW_SETUP_WIZARD = try container.decodeIfPresent(Bool.self, forKey: .SHOW_SETUP_WIZARD) ?? false
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case VERSION
        case SHOW_SETUP_WIZARD
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(VERSION, forKey: .VERSION)
        try container.encode(SHOW_SETUP_WIZARD, forKey: .SHOW_SETUP_WIZARD)
    }
}

